### ISSUE TITLE
Don't work in Windows 7 SP 1 with .Net Framework 4.7

### ISSUE THREAD

**Issue by DorianB2017** [OfficeDev/office-custom-ui-editor#2]
Hello!
Your application "office-custom-ui-editor" don't work in Windows 7 SP 1 with .Net Framework 4.7.
If I run/execute "setup.exe", the following message appears: 

"PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2117.0 built by: NET47REL1LAST
	clr.dll 			: 4.7.2117.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2117.0 built by: NET47REL1LAST
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///D:/office-custom-ui-editor-master/publish/CustomUIEditor.application

IDENTITIES
	Deployment Identity		: CustomUIEditor.application, Version=4.0.0.0, Culture=neutral, PublicKeyToken=33912883cf997d7f, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\office-custom-ui-editor-master\publish\CustomUIEditor.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from file:///D:/office-custom-ui-editor-master/publish/Application%20Files/CustomUIEditor_4_0_0_0/CustomUIEditor.exe.manifest: the manifest may not be valid or the file could not be opened.
		+ Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x8007001f
			 Start line: 	0
			 Start column: 	0
			 Host file: 	
		+ A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [03.02.2018 10:01:33] : Activation of D:\office-custom-ui-editor-master\publish\CustomUIEditor.application has started.
	* [03.02.2018 10:01:33] : Processing of deployment manifest has successfully completed.
	* [03.02.2018 10:01:33] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [03.02.2018 10:01:33] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file:///D:/office-custom-ui-editor-master/publish/Application%20Files/CustomUIEditor_4_0_0_0/CustomUIEditor.exe.manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x8007001f
			 Start line: 	0
			 Start column: 	0
			 Host file: 	
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)
			at System.Deployment.Application.Manifest.AssemblyManifest..ctor(FileStream fileStream)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Runtime.InteropServices.COMException
		- A device attached to the system is not functioning. (Exception from HRESULT: 0x8007001F)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IsolationInterop.CreateCMSFromXml(Byte[] buffer, UInt32 bufferSize, IManifestParseErrorCallback Callback, Guid& riid)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available."

, and if I run/execute directly "CustomUIEditor.application" from "publish\Application Files\CustomUIEditor_4_0_0_0\", the message is:

”PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2117.0 built by: NET47REL1LAST
	clr.dll 			: 4.7.2117.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2117.0 built by: NET47REL1LAST
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///D:/office-custom-ui-editor-master/publish/Application%20Files/CustomUIEditor_4_0_0_0/CustomUIEditor.application
	Deployment Provider url		: http://dimarti-devt/CustomUIEditor/CustomUIEditor.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\office-custom-ui-editor-master\publish\Application Files\CustomUIEditor_4_0_0_0\CustomUIEditor.application resulted in exception. Following failure messages were detected:
		+ Downloading http://dimarti-devt/CustomUIEditor/CustomUIEditor.application did not succeed.
		+ The remote name could not be resolved: 'dimarti-devt'

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [03.02.2018 10:03:00] : Activation of D:\office-custom-ui-editor-master\publish\Application Files\CustomUIEditor_4_0_0_0\CustomUIEditor.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [03.02.2018 10:03:02] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://dimarti-devt/CustomUIEditor/CustomUIEditor.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote name could not be resolved: 'dimarti-devt'
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.”

**Comment by seadoggie01** [comment]
Similar error with Windows 10, .NET Version 4.7.3 :(
